fn main() {
  // Declaring the app's commands makes each one a permission, so the webview
  // can only call what capabilities/default.json grants.
  let commands = tauri_build::AppManifest::new().commands(&[
    "get_global_shortcut",
    "set_global_shortcut",
    "pause_global_shortcut",
    "get_launch_at_login",
    "set_launch_at_login",
    "update_tray_pomodoro",
    "get_vault_status",
    "pick_vault",
    "list_vault",
    "read_vault_file",
    "write_vault_file",
    "watch_vault",
    "terminal_list",
    "terminal_open",
    "terminal_attach",
    "terminal_restart",
    "terminal_close",
    "terminal_write",
    "terminal_resize",
    "portal_show",
    "portal_hide",
    "portal_fade_out",
    "portal_nav",
    "portal_open_external",
    "portal_sign_out",
    "portal_remove",
    "portal_prune",
    "harness_env_status",
    "harness_install_runtime",
    "harness_get_config",
    "harness_set_config",
    "harness_set_key",
    "harness_discover",
    "harness_probe",
    "harness_dsh_start",
    "harness_acp_open_session",
    "harness_claude_start",
    "harness_send",
    "harness_kill",
    "harness_reset",
    "harness_pick_folder",
    "harness_create_project",
    "harness_state_load",
    "harness_state_save",
    "harness_chat_load",
    "harness_chat_save",
    "harness_chat_delete",
  ]);
  tauri_build::try_build(tauri_build::Attributes::new().app_manifest(commands))
    .expect("failed to run tauri-build");
}
