/**
 * The app ships with a set of starter categories. They used to exist only in
 * client memory, with hand-written ids like "work" and "salary", which meant a
 * task filed under one sent `category_id: "work"` to a uuid column and the
 * insert was rejected. They have to be real rows before anything can reference
 * them.
 *
 * Seeding happens client-side rather than in the migration because `user_id`
 * defaults to `auth.uid()`, which is null in the SQL editor — the rows can only
 * be created by an authenticated client.
 */

export type CategoryTable = "task_categories" | "financial_categories";

export interface CategoryRow {
  id: string;
  name: string;
  color: string;
}

export interface DefaultCategory {
  name: string;
  color: string;
}

/** The slice of the Supabase client this module needs, narrowed for testing. */
export interface CategoryClient {
  from(table: CategoryTable): {
    insert(rows: DefaultCategory[]): {
      select(): Promise<{ data: CategoryRow[] | null; error: { message: string } | null }>;
    };
  };
}

/**
 * Creates the starter categories for the signed-in user and returns them with
 * the ids the database assigned. Returns null if the insert fails, so the
 * caller can decide whether that is fatal.
 *
 * Only `name` and `color` are sent: `id` is generated by the database, and
 * `user_id` comes from its `default auth.uid()`.
 */
export async function seedDefaultCategories(
  client: CategoryClient,
  table: CategoryTable,
  defaults: readonly DefaultCategory[],
): Promise<CategoryRow[] | null> {
  const { data, error } = await client
    .from(table)
    .insert(defaults.map(({ name, color }) => ({ name, color })))
    .select();

  if (error || !data) return null;
  return data;
}
